import RightSidebar from "@/Components/RightSidebar/RightSidebar";
import LeftSidebar from "../Components/LeftSidebar/LeftSidebar";

import "./globals.css";
import { Inter } from "next/font/google";
import useTwitModal from "@/Hooks/useTwitModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LeftSidebar />
        {children}
        <RightSidebar />
      </body>
    </html>
  );
}
